/**
 * TypeEase — corpus.js
 * ════════════════════════════════════════════════════════════════
 * This file should be GENERATED by build_corpus.py using the real
 * Birkbeck + Holbrook spelling corpora.
 *
 * HOW TO GENERATE:
 * ────────────────
 * 1. Download missp.dat from:
 *    https://titan.dcs.bbk.ac.uk/~roger/missp.dat
 *
 * 2. (Optional, recommended) Download holbrook-missp.dat from the
 *    same page — adds frequency weighting.
 *
 * 3. Run the build script:
 *    python3 build_corpus.py missp.dat holbrook-missp.dat
 *
 * 4. Replace THIS file with the generated corpus.js
 *
 * WHAT IT CONTAINS (when generated):
 * ────────────────────────────────────
 * 36,133 misspelling → correct word pairs from real human writers,
 * frequency-weighted and ADHD-error-type classified.
 *
 * Format: window.TYPEEASE_CORPUS = { "misspeling": ["misspelling", score, "T"] }
 * Types: T=Transposition D=Doubling O=Omission I=Insertion S=Substitution B=Boundary
 *
 * WITHOUT THIS FILE:
 * ──────────────────
 * The extension still works using:
 *   - The built-in dictionary (~200 ADHD-specific pairs in content.js)
 *   - The Damerau-Levenshtein BK-tree engine (catches novel typos)
 *   - The geminate auto-fix module (catches doubling errors)
 *
 * ════════════════════════════════════════════════════════════════
 */

// Placeholder — no corpus loaded yet.
// content.js will detect window.TYPEEASE_CORPUS === undefined and
// fall back to built-in dictionary + DL engine.
window.TYPEEASE_CORPUS = undefined;
